# -*- coding: utf-8 -*-
"""Poem Generation Using RNN and LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ayush120/poem-generation-using-rnn-and-lstm.79f4a728-3005-4611-84f2-e74e415327d5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260330/auto/storage/goog4_request%26X-Goog-Date%3D20260330T175649Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7a3a7f1c6f647e2eeea0660045bd077c23e206318c44c8f90e4f9c5e753016d8c7d1f5f3e1729c86e3aada7969f01927b901da78502d9feda0c899ef578ea6e46ae1a00a709389969ba383b0e0f6e7dc6df1941b9fe1507f40b8ca6cbca4528c33f14e4421412988351f1f560bcb79332f231e270bddd0972537df6aff2e9b1a9b9d523632c632b36982093007b2fbb8da5a31b893ba17ac47dffaf49f2a27a559f802e845250648c05b1de8bc2b728855d268418e30b7cc1ca00e385e12a09742f6b5f5b43601d1cf8075be055f7a23e7666e48e4a7a4539873398347b00731e175216d3be73f02c1bf9a050f12a33f2ac1693bd843403c6113e81ac2b10aa3
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

ayush120_poems_dataset_path = kagglehub.dataset_download('ayush120/poems-dataset')

print('Data source import complete.')

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import csv
import time
import json

# Load the Dataset

text = ""
with open("/kaggle/input/datasets/ayush120/poems-dataset/poems-100.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        text += " ".join(row) + " "

# Tokenize the Text into Words

tokens = text.split()

# Create a Dictionary to Map Words to Indices

word_to_idx = {}
idx_to_word = {}
vocab_size = 0

for word in tokens:
    if word not in word_to_idx:
        word_to_idx[word] = vocab_size
        idx_to_word[vocab_size] = word
        vocab_size += 1

# Convert Tokens to Indices

token_indices = [word_to_idx[word] for word in tokens]

print(f"Vocabulary Size: {vocab_size}")

# Create Sequences and Targets

seq_length = 10
sequences = []
targets = []

for i in range(len(token_indices) - seq_length):
    seq = token_indices[i:i + seq_length]
    target = token_indices[i + seq_length]
    sequences.append(seq)
    targets.append(target)

# Convert to PyTorch Tensors

sequences = torch.tensor(sequences, dtype=torch.long)
targets = torch.tensor(targets, dtype=torch.long)

# Define One-Hot Encoding for RNN Model

class OneHotRNN(nn.Module):
    def __init__(self, vocab_size, hidden_dim, output_dim):
        super(OneHotRNN, self).__init__()
        self.rnn = nn.RNN(vocab_size, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        output, _ = self.rnn(x)
        out = self.fc(output[:, -1, :])
        return out

# Define LSTM Model with Embedding Layer

class PoemLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, output_dim):
        super(PoemLSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        output, _ = self.lstm(embedded)
        out = self.fc(output[:, -1, :])
        return out

# Hyperparameters

embed_dim = 100
hidden_dim = 128
output_dim = vocab_size

# Initialize Models

onehot_model = OneHotRNN(vocab_size, hidden_dim, output_dim)
embedding_model = PoemLSTM(vocab_size, embed_dim, hidden_dim, output_dim)

criterion = nn.CrossEntropyLoss()
onehot_optimizer = optim.Adam(onehot_model.parameters(), lr=0.001)
embedding_optimizer = optim.Adam(embedding_model.parameters(), lr=0.001)

# Loss Tracking

onehot_losses, embedding_losses = [], []

# T raining Function

def train_model(model, optimizer, name):
    start_time = time.time()
    for epoch in range(100):
        total_loss = 0
        for i in range(0, len(sequences), 32):
            batch_seq = sequences[i:i + 32]
            batch_target = targets[i:i + 32]

            # One-Hot Encoding for OneHotRNN
            if name == "OneHotRNN":
                batch_seq = F.one_hot(batch_seq, num_classes=vocab_size).float()

            # Forward Pass
            outputs = model(batch_seq)
            loss = criterion(outputs, batch_target)

            # Backward Pass and Optimization
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / (len(sequences) // 32)
        if name == "OneHotRNN":
            onehot_losses.append(avg_loss)
        else:
            embedding_losses.append(avg_loss)

        print(f"{name} Epoch [{epoch+1}/100], Avg Loss: {avg_loss:.4f}")
    print(f"{name} Training Time: {time.time() - start_time:.2f}s\n")

# Train Both Models

train_model(onehot_model, onehot_optimizer, "OneHotRNN")
train_model(embedding_model, embedding_optimizer, "EmbeddingLSTM")

# Poem Generation Function (Testing)

def generate_poem(model, seed_text, num_words=50, model_type="EmbeddingLSTM"):
    model.eval()
    words = seed_text.split()
    with torch.no_grad():
        for _ in range(num_words):
            seq = [word_to_idx.get(word, 0) for word in words[-seq_length:]]
            seq = torch.tensor(seq, dtype=torch.long).unsqueeze(0)

            if model_type == "OneHotRNN":
                seq = F.one_hot(seq, num_classes=vocab_size).float()

            output = model(seq)
            probabilities = F.softmax(output, dim=1)
            predicted_idx = torch.multinomial(probabilities, 1).item()

            words.append(idx_to_word[predicted_idx])

    return " ".join(words)

# Test Generation

seed_text = "I wandered lonely as a"
print("\nGenerated Poem (OneHotRNN):", generate_poem(onehot_model, seed_text, model_type="OneHotRNN"))
print("\nGenerated Poem (EmbeddingLSTM):", generate_poem(embedding_model, seed_text, model_type="EmbeddingLSTM"))

# Exporting Models

print("\n" + "="*60)
print("EXPORTING MODELS")
print("="*60)

# Save OneHotRNN

torch.save({
    'model_state_dict': onehot_model.state_dict(),
    'vocab_size': vocab_size,
    'hidden_dim': hidden_dim,
}, 'onehot_rnn.pt')
print("✅ Saved onehot_rnn.pt")

# Save EmbeddingLSTM

torch.save({
    'model_state_dict': embedding_model.state_dict(),
    'vocab_size': vocab_size,
    'embed_dim': embed_dim,
    'hidden_dim': hidden_dim,
}, 'embedding_lstm.pt')
print("✅ Saved embedding_lstm.pt")

# Save Vocabulary

vocab_data = {
    'word_to_idx': word_to_idx,
    'idx_to_word': {str(k): v for k, v in idx_to_word.items()},
}
with open('vocab.json', 'w', encoding='utf-8') as f:
    json.dump(vocab_data, f)
print("✅ Saved vocab.json")